sudo: required
services:
  - docker

before_install:
  - docker build -t feis2019/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true feis2019/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "s3"
  bucketh_path: "docker-react"
  on
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "AWS_SECRET_KEY"